import{a as u,S as p,i as l}from"./assets/vendor-VVWBAj3V.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const d="55520229-6b38dd18315a985816c1e4a23",f="https://pixabay.com/api/";function m(r){return u(f,{params:{key:d,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(({data:s})=>s)}const i=document.querySelector(".gallery"),c=document.querySelector(".loader"),y=new p(".gallery-item a",{captionDelay:1e3,captionsData:"alt"});function g(r){const s=r.map(n=>`
          <li class="gallery-item">
          <a class="gallery-thumb" href="${n.largeImageURL}"><img class="gallery-img" src="${n.webformatURL}" alt="${n.name}" /></a>
          <ul class="gallery-content-list">
            <li class="gallery-content-item"><span>Likes</span><span>${n.likes}</span></li>
            <li class="gallery-content-item"><span>Views</span><span>${n.views}</span></li>
            <li class="gallery-content-item"><span>Comments</span><span>${n.comments}</span></li>
            <li class="gallery-content-item"><span>Downloads</span><span>${n.downloads}</span></li>
          </ul>
      </li>`).join("");i.insertAdjacentHTML("beforeend",s),y.refresh()}function h(){i.innerHTML=""}function L(){c.classList.remove("is-hidden")}function b(){c.classList.add("is-hidden")}const S=document.querySelector(".form");document.querySelector(".gallery");l.settings({pauseOnHover:!0,position:"topRight"});S.addEventListener("submit",v);function v(r){r.preventDefault();const{["search-text"]:s}=r.target.elements;s.value!==""&&(h(),L(),m(s.value).then(w).catch(console.log).finally(b))}function w(r){r.hits.length||l.error({message:"Sorry, there are no images matching your search query. Please try again!"}),g(r.hits)}
//# sourceMappingURL=index.js.map
